### ISSUE TITLE
jenv: no such command `enable-plugin'

### ISSUE THREAD

**Issue by brksrly** [samsonnguyen/puppet-solium#14] opened 2015-04-06 22:01 UTC
When running boxen I got the following error:

Debug: Exec[jenv-ant](provider=posix): Executing check 'test -e /Users/brooks.riley/.jenv/shims/ant'
Debug: Executing 'test -e /Users/brooks.riley/.jenv/shims/ant'
Debug: Exec[jenv-ant](provider=posix): Executing 'jenv enable-plugin ant'
Debug: Executing 'jenv enable-plugin ant'
Notice: /Stage[main]/Solium/Exec[jenv-ant]/returns: jenv: no such command `enable-plugin'
Error: jenv enable-plugin ant returned 1 instead of one of [0]
Error: /Stage[main]/Solium/Exec[jenv-ant]/returns: change from notrun to 0 failed: jenv enable-plugin ant returned 1 instead of one of [0]

I was able to circumvent the issue by running: 
yyc-briley-mp:repo brooks.riley$ jenv enable-plugin ant
Outside of boxen.

**Comment by brksrly** [comment] 2015-04-06 22:04
If not broken you can replicate with 
`yyc-briley-mp:repo brooks.riley$ jenv disable-plugin ant`

**Comment by samsonnguyen** [comment] 2015-04-06 22:10
Two issues:
- We are running the exec command twice.
  - once in manifests/init.pp
  - second time in manifests/jenv.pp
- jenv binary cannot be found, likely because of path issues

**Comment by samsonnguyen** [comment] 2015-04-06 22:54
I think i figured it out,

It has to do with the way commands are parsed in jenv

/opt/boxen/homebrew/Cellar/jenv/0.4.2/libexec/libexec/jenv

```
command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(jenv --version)\n$(jenv-help)" >&2
  ;;
* )
  command_path="$(command -v "jenv-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "jenv: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
```

The problem is the script name is called

/opt/boxen/homebrew/Cellar/jenv/0.4.2/libexec/libexec/jenv-sh-enable-plugin

```
ls /opt/boxen/homebrew/Cellar/jenv/0.4.2/libexec/libexec/
```

**Comment by samsonnguyen** [comment] 2015-04-06 22:55
Changing the manifest to execute this seems to work

```
  exec { 'install jenv ant plugin':
    command => 'jenv sh-enable-plugin ant',
    user    => $user,
    creates => "${home}/.jenv/shims/ant",
    require => Package['jenv']
  }
```

**Comment by samsonnguyen** [comment] 2015-04-07 21:17
Closing issue

**Closed as completed** 2015-04-07 21:17 UTC
